# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: update

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '00 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r ./requirements.txt
      shell: bash
    - name: Install OS specific deps
      run:   |
         sudo apt update && sudo apt install libzbar-dev
      shell: bash
    - name: update 
      run: |
         python scraper/denylist.py
      shell: bash
    - name: Commit files
      run: |
          git config --local user.email "thomas@tphil.nl"
          git config --local user.name "Thomas (Action)"
          git add .
          git commit -m "Automatic update"
      continue-on-error: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
      continue-on-error: true
